### ISSUE TITLE
[pyrad] Bug:

### ISSUE THREAD

**Issue by sandrineperrin** [thriqon/mulled#28]
Hey, I have make some test. PyRAD and vsearch dependencies are nonfunctional. It's missing the library : libstdc++.so.6 at /usr/lib. With the package, it is ok. Thanks,

**Comment by thriqon** [comment]
I forced a rebuild, does the issue go away?

Please remove the image before testing again, as it shares the name of the old version:

`docker rmi quay.io/mulled/pyrad:3.0.64--py27_0`
`docker run -it --rm quay.io/mulled/pyrad:3.0.64--py27_0`

**Comment by sandrineperrin** [comment]
It's functionnal right now. Thank you
